Draft layout
buildo/YelpLike-andrea pull request #2
Opened 2023-09-27 15:32 UTC by GorlemZ

https://buildo.atlassian.net/browse/TE-113

2023-09-28 15:23 UTC, GorlemZ commented
In this PR: the first view with i18n and a draft of the router (tbd) with mocked data

I'm not sure I'm structuring the right way with the Router: my intent is to have the same layout with both views, changing only the "internal" components when changing route. I'm not sure how I'll gonna manage the data flow, nor if it is the right design for this simple app.
Any advice is welcome.

2023-09-28 15:28 UTC, federico-ercoles commented
It seems like you need a rebase on `main`. 😉

2023-09-29 08:06 UTC, federico-ercoles commented
A couple of things:

1. You merged `main` into this branch instead of rebasing this branch onto `main`. Both are valid approaches, but the latter allows you to have a cleaner commit history. Is there a specific reason why you went with the merge?
2. Your Router structure is correct, although on more complex projects we prefer to create the router with the [`createBrowserRouter`](https://reactrouter.com/en/main/routers/create-browser-router) utility, to separate that from the actual component definition. For this project, your approach is fine, but I would suggest reading a bit about the other if you have the time so that you can familiarize yourself with it.

2023-09-29 08:52 UTC, federico-ercoles requested changes

2023-09-29 08:52 UTC, federico-ercoles commented on src/App.tsx
> +        <Box>
This `Box` is redundant.

2023-09-29 08:52 UTC, federico-ercoles commented on src/components/RestaurantPreview.tsx
> +import "@buildo/bento-design-system/defaultTheme.css";
You shouldn't need to import styling in every component, the import in `App` should be sufficient.

2023-09-29 08:52 UTC, federico-ercoles commented on src/components/RestaurantPreview.tsx
> +  image_url: string;
Standard case style for JS/TS is camel case
```suggestion
  imageUrl: string;
```

2023-09-29 08:52 UTC, federico-ercoles commented on src/components/RestaurantPreview.tsx
> +            {`${t("Card.Rating")}: ${rating} ★`}
You can integrate this string's structure in the localized text, look into [interpolation](https://www.i18next.com/translation-function/interpolation).

2023-09-29 08:52 UTC, federico-ercoles commented on src/i18n.ts
> +export const defaultNS = "ns1";
With only one localization file, you could use the default react-i18next namespace, which is `translation`.

2023-09-29 08:52 UTC, federico-ercoles commented on src/pages/Home.tsx
> +    })
This is minor, but when building an array of the same component, you should give each one a unique `key` attribute ([ref](https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key)): right now this only serves to silence those noisy warnings you get in console, but in the long run this is important if your list can change (e.g. by sorting or by inserting/deleting elements).

2023-09-29 08:52 UTC, federico-ercoles commented on src/pages/Home.tsx
Other minor comment: I notice some inconsistency in the indentation of the code. In some files you have a spacing of 2, in others (like this one) of 4. If you have time, look into some code formatter like [prettier](https://prettier.io), or see if your code editor already offer something like that.

2023-09-29 08:52 UTC, federico-ercoles commented on src/pages/Home.tsx
> +            <Body size="large">
This `Body` should not be needed, you're already setting the typography inside each card component.

2023-09-29 09:56 UTC, GorlemZ commented
Thanks @federico-ercoles for the deep review 🙏
I'll make changes accordingly now. About the merge: I've always used it for better history traceability given that I always prefer to keep the merged branches. I've tried the squash alt for the same reason. Of course I'll use the best buildo practice from now on 🌈

2023-09-29 10:34 UTC, GorlemZ commented on src/pages/Home.tsx
I already had Prettier installed and configured, somehow only the Home file was connected to another Formatter. I hadn't even noticed! Thanks

2023-09-29 11:05 UTC, federico-ercoles commented on src/data-model/RestaurantDetails.tsx
I just noticed this empty file, I would remove it.

2023-09-29 11:05 UTC, federico-ercoles commented on src/i18n.ts
> +  defaultNS: "translation",
Minor: `translation` is already the built-in default namespace ([ref](https://www.i18next.com/overview/configuration-options)), so this line should be redundant.

2023-09-29 11:05 UTC, federico-ercoles commented on src/pages/Home.tsx
> +    </Box>
Do you actually need to specify `height` for this component? I get why you need it in the sidebar content, since it's reasonable to assume it would be smaller than the page content, but here the tiles should already be expanding as needed.

```suggestion
    <Inset space={16}>
      <Tiles space={16} columns={3} alignY={"bottom"}>
        {mockCards}
      </Tiles>
    </Inset>
```

2023-09-29 11:05 UTC, federico-ercoles commented on src/App.tsx
> +        </Headline>
I would add a bit of padding around this title, and maybe a colored background to better separate this heading from the page content.

2023-09-29 11:05 UTC, federico-ercoles commented on src/App.tsx
> +        </ContentWithSidebar>
An observation of the routing structure: right now, if you were to navigate to a different route, you would still see the sidebar with the filters, but it wouldn't make much sense to have that in a detail view. I would move the sidebar structure inside the `Home` component.

2023-10-02 09:44 UTC, federico-ercoles approved these changes, later dismissed
🚀

2023-10-02 15:00 UTC, GorlemZ commented
@federico-ercoles rebased to the latest commit before adding filters

2023-10-02 15:01 UTC, federico-ercoles approved these changes

2023-10-02 15:02 UTC, merged